### ISSUE TITLE
cpuStress.sh uses sensors, but doesn't attempt to install it

### ISSUE THREAD

**Issue by clayboone** [cresource/GCC#1]
The meat of scripts shouldn't be installing any programs in the first place, but since this one is already installing a bunch, why not also check for and install `sensors` as it's not installed by default on my Ubuntu 16.10

**Comment by JonathanCoffey** [comment]
where am I...

**Comment by TheInfoGuru** [comment]
Bug fixed. Now checks for sensors program.
